version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
#  redis:
#    image: "redis:alpine"
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --client-output-buffer-limit pubsub 512mb 128mb 60
  celery:
    build: .
    #command: celery -A celery_worker --loglevel=info
    #command: celery -A celery_worker.celery_app worker --loglevel=info
    command: celery -A celery_worker.celery_app worker --loglevel=DEBUG --pool=gevent --autoscale=100000,100
    depends_on:
      - redis
  flower:
    image: mher/flower
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
